### ISSUE TITLE
Observing build issue while trying to emulate LinuxBoot with qemu

### ISSUE THREAD

**Issue by Amar-Bharamshetti** [linuxboot/linuxboot#33]
I am observing below error with 'make run' command,

root@xxxlab-9:/home/ubuntu/linuxboot# uname -a
Linux xxxlab-9 4.4.0-116-generic #140-Ubuntu SMP Mon Feb 12 21:23:04 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
root@xxxlab-9:/home/ubuntu/linuxboot# lsb
lsblk        lsb_release  
root@xxxlab-9:/home/ubuntu/linuxboot# lsb
lsblk        lsb_release  
root@xxxlab-9:/home/ubuntu/linuxboot# lsb_release  -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 16.04.4 LTS
Release:	16.04
Codename:	xenial
root@xxxlab-9:/home/ubuntu/linuxboot# uname -a
Linux xxxlab-9 4.4.0-116-generic #140-Ubuntu SMP Mon Feb 12 21:23:04 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
root@xxxlab-9:/home/ubuntu/linuxboot# make run
make: *** No rule to make target 'bzImage', needed by 'build/qemu/Linux.ffs'.  Stop.
root@xxxlab-9:/home/ubuntu/linuxboot# 

Any help to resolve this issue is appreciated.

**Comment by osresearch** [comment]
You'll need to provide a kernel to bundle into the LinuxBoot image with the `KERNEL=../../path/to/bzImage` (and optionally an initramfs cpio file with `INITRD=../../path/to/initrd.cpio.xz`).

If you're just experimenting it might be easier to build the Heads `qemu-linuxboot` target, which will make a kernel, initrd and LinuxBoot ROM image.

```
git checkout https://github.com/osresearch/heads
make -C heads BOARD=qemu-linuxboot
```

(and wait for a while, since it will build gcc, libc, Linux, edk2, and the entire runtime system)

**Comment by Amar-Bharamshetti** [comment]
Thank you. This works.

I tried with below command, 

git clone https://github.com/osresearch/heads.git
make -C heads BOARD=qemu-linuxboot

**Comment by ReLIFE9527** [comment]
Hi,
Did your linuxboot running on qemu complete the whole boot process?
I am stuck in the recovery shell with the message showing "Unable to mount /boot", and have no idea how to configure it to boot the real kernel and filesystem. Could you share some experience with running linuxboot on qemu?
Any reply will be appreciated.
